from . import cattle_detail
from . import cattle_health
from . import cattle_feed
from . import cattle_housing
from . import cattle_milk
from . import cattle_administrator
from . import cattle_doctor
from . import cattle_payment
from . import product_product
from . import cattle_sale_order_line
from . import cattle_sale_order
